apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  ## serves as a connecting method by the service to
  ## know wich pods are registered with it
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
  ## this applies to the pods
    metadata:
      labels:
        app: nginx
    spec:
    ## blueprint for the pod
      containers:
      - name: nginx
        image: nginx:1.16
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        ## this should match the service target port
        - containerPort: 8080
