apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app.kubernetes.io/name: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  selector:
    app.kubernetes.io/name: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8087
